[build]
  # Dossier contenant les fichiers à déployer
  publish = "."
  
  # Pas de commande de build nécessaire pour HTML pur
  command = ""

# Redirections pour SPA (Single Page Application)
# Utile si tu ajoutes des routes plus tard
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité recommandés
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://code.iconify.design; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://images.unsplash.com https://picsum.photos; connect-src 'self' https://calendly.com;"
    
# Cache pour les images
[[headers]]
  for = "/assets/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache pour CSS/JS
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache pour les fonts
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache pour les images CDN
[[headers]]
  for = "https://images.unsplash.com/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Optimisation pour les performances
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Content-Type-Options = "nosniff"

# Compression
[[headers]]
  for = "/*"
  [headers.values]
    Content-Encoding = "gzip"
